apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: heicconverter
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: heic.mwalden.tech
    http:
      paths:
      - path: /
        backend:
          serviceName: heicconverter
          servicePort: 2000